app:
    baseUrl: http://app.carrot.re

spring:
    profiles: prod

    thymeleaf:
        cache: true
        mode: LEGACYHTML5

    datasource:
        url: jdbc:postgresql://localhost:5432/carrot
        username: bfolder
        initial-size: 5
        max-active: 10
        min-idle: 2
        max-idle: 5
        validation-query: "SELECT 1"
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
        remove-abandoned: true

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        open-in-view: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate:
                generate_statistics: false
                cache:
                    use_second_level_cache: true
                    use_query_cache: false

logging:
    level:
        org.springframework: ERROR
        org.hibernate: ERROR
