app:
    baseUrl: http://app.carrot.re

spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate:
                generate_statistics: false
                cache:
                    use_second_level_cache: true
                    use_query_cache: false

    mail:
        host: mail.carrot.re
logging:
    level:
        org.springframework: ERROR
        org.hibernate: ERROR
            