spring:
    profiles: dev

    thymeleaf:
        cache: true
        mode: LEGACYHTML5

    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/carrot
        username: root
        password: root
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    mail:
        smtp:
            host: localhost
            port: 1025
            from: mail@boxedfolder.com

logging:
    level:
        org.springframework: INFO
        org.hibernate: INFO
