spring:
    profiles:
        active: dev

    thymeleaf:
        mode: LEGACYHTML5

    mail:
        host: localhost
        port: 1025
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: noreply@carrot.re
        smtp:
            host: localhost
            port: 1025
            from: noreply@carrot.re