app:
    baseUrl: http://app.carrot.re

spring:
    profiles: test

    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:sampletest;MODE=MySQL

    mail:
        smtp:
            host: localhost
            port: 1025
            from: noreply@carrot.re