app:
    baseUrl: http://localhost:9000

spring:
    profiles: dev

    thymeleaf:
        cache: true
        mode: LEGACYHTML5

    datasource:
        url: jdbc:postgresql://localhost:5432/carrot
        username: bfolder

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        open-in-view: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate:
                generate_statistics: false
                cache:
                    use_second_level_cache: true
                    use_query_cache: false
    mail:
        smtp:
            port: 1025
        port: 1025

logging:
    level:
        org.springframework: INFO
        org.hibernate: INFO
