spring:
    profiles:
        active: dev

    thymeleaf:
        mode: LEGACYHTML5

    jpa:
        properties:
            hibernate:
                current_session_context_class: "org.springframework.orm.hibernate4.SpringSessionContext"


    mail:
        host: localhost
        port: 1025
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: noreply@carrot.re
        smtp:
            host: localhost
            port: 1025
            from: noreply@carrot.re