app:
    baseUrl: http://app.carrot.re

spring:
    profiles: prod

    thymeleaf:
        cache: true
        mode: LEGACYHTML5

    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/carrot_production?autoReconnect=true
        username: carrot_prod
        password: xxxx
        initialSize: 34
        maxActive: 377
        maxIdle: 233
        minIdle: 89
        timeBetweenEvictionRunsMillis: 34000
        minEvictableIdleTimeMillis: 55000
        validationQuery: "SELECT 1"
        validationInterval: 34000
        testOnBorrow: true
        removeAbandoned: true
        removeAbandonedTimeout: 55

    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate:
                generate_statistics: false
                cache:
                    use_second_level_cache: true
                    use_query_cache: false

logging:
    level:
        org.springframework: ERROR
        org.hibernate: ERROR
