spring:
    profiles:
        active: dev

    thymeleaf:
        mode: LEGACYHTML5

    mail:
        host: localhost
        port: 25
        username: noreply@carrot.re
        password: xxxxx
        protocol: smtp
        tls: false
        auth: true
        from: noreply@carrot.re
        smtp:
            host: localhost
            port: 25
            from: noreply@carrot.re